# Generated by Django 4.2.7 on 2026-05-17 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGitHubToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='GitHub OAuth access token', max_length=255)),
                ('token_type', models.CharField(default='Bearer', help_text="Token type (usually 'Bearer')", max_length=50)),
                ('scope', models.CharField(blank=True, help_text="OAuth scopes granted (e.g., 'user,repo')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the token was created')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiration date (if applicable)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is currently active')),
                ('user', models.OneToOneField(help_text='User who owns this GitHub token', on_delete=django.db.models.deletion.CASCADE, related_name='github_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Token',
                'verbose_name_plural': 'GitHub Tokens',
                'db_table': 'github_tokens',
                'indexes': [models.Index(fields=['is_active'], name='github_toke_is_acti_533554_idx')],
            },
        ),
    ]
