# Generated by Django 4.2.7 on 2026-05-17 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(help_text='Name of the GitHub repository', max_length=255)),
                ('repository_owner', models.CharField(help_text='Owner/organization of the repository', max_length=255)),
                ('repository_url', models.URLField(help_text='Full URL to the GitHub repository', max_length=500)),
                ('branch_name', models.CharField(default='main', help_text='Branch being analyzed', max_length=100)),
                ('file_count', models.IntegerField(default=0, help_text='Number of files in this session (max 5)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='pending', help_text='Current status of the analysis', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the session was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the analysis was completed', null=True)),
                ('user', models.ForeignKey(help_text='User who created this analysis session', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'Analyse",
                'verbose_name_plural': "Sessions d'Analyse",
                'db_table': 'analysis_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='Executive summary of the security analysis')),
                ('total_vulnerabilities', models.IntegerField(default=0, help_text='Total number of vulnerabilities across all files')),
                ('critical_count', models.IntegerField(default=0, help_text='Number of critical severity vulnerabilities')),
                ('high_count', models.IntegerField(default=0, help_text='Number of high severity vulnerabilities')),
                ('medium_count', models.IntegerField(default=0, help_text='Number of medium severity vulnerabilities')),
                ('low_count', models.IntegerField(default=0, help_text='Number of low severity vulnerabilities')),
                ('recommendations', models.JSONField(default=list, help_text='List of security recommendations (JSON format)')),
                ('security_score', models.FloatField(default=0.0, help_text='Overall security score (0.0 to 10.0)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When the report was generated')),
                ('session', models.OneToOneField(help_text='Analysis session this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='security_report', to='analyzer.analysissession')),
            ],
            options={
                'verbose_name': 'Rapport de Sécurité',
                'verbose_name_plural': 'Rapports de Sécurité',
                'db_table': 'security_reports',
            },
        ),
        migrations.CreateModel(
            name='FileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Relative path to the file in the repository', max_length=500)),
                ('file_name', models.CharField(help_text="Name of the file (e.g., 'app.py')", max_length=255)),
                ('file_extension', models.CharField(help_text="File extension (e.g., '.py', '.js')", max_length=50)),
                ('is_auto_selected', models.BooleanField(default=False, help_text='True if auto-selected by IBM Bob AI, False if manually added')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_content', models.TextField(blank=True, help_text='Content of the file (optional, for caching)')),
                ('analysis_result', models.JSONField(default=dict, help_text='IBM Bob AI analysis result (JSON format)')),
                ('vulnerabilities_count', models.IntegerField(default=0, help_text='Total number of vulnerabilities found')),
                ('severity_level', models.CharField(choices=[('critical', 'Critique'), ('high', 'Élevé'), ('medium', 'Moyen'), ('low', 'Faible'), ('info', 'Information')], default='info', help_text='Highest severity level found in this file', max_length=20)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, help_text='When the analysis was performed')),
                ('analysis_order', models.IntegerField(default=0, help_text='Order in which this file was analyzed (1-5)')),
                ('session', models.ForeignKey(help_text='Analysis session this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='file_analyses', to='analyzer.analysissession')),
            ],
            options={
                'verbose_name': 'Analyse de Fichier',
                'verbose_name_plural': 'Analyses de Fichiers',
                'db_table': 'file_analyses',
                'ordering': ['analysis_order', 'analyzed_at'],
                'indexes': [models.Index(fields=['session', 'analysis_order'], name='file_analys_session_61494d_idx'), models.Index(fields=['is_auto_selected'], name='file_analys_is_auto_de93d6_idx')],
                'unique_together': {('session', 'file_path')},
            },
        ),
        migrations.AddIndex(
            model_name='analysissession',
            index=models.Index(fields=['user', '-created_at'], name='analysis_se_user_id_aa58d1_idx'),
        ),
        migrations.AddIndex(
            model_name='analysissession',
            index=models.Index(fields=['status'], name='analysis_se_status_e5934c_idx'),
        ),
    ]
