# Generated by Django 4.2.7 on 2026-05-17 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysissession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created this analysis session (optional for MVP)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
